export interface LexiconEntry {
  source: string;
  target: string;
  gloss: string;
  level: number;
}

export const LOCAL_LEXICON: LexiconEntry[] = [
  { source: "不可或缺", target: "indispensable", gloss: "不可缺少的", level: 6 },
  { source: "错综复杂", target: "intricate", gloss: "复杂且相互关联的", level: 6 },
  { source: "细致入微", target: "nuanced", gloss: "细腻且有层次的", level: 6 },
  { source: "模棱两可", target: "ambiguous", gloss: "含义不明确的", level: 6 },
  { source: "人工智能", target: "artificial intelligence", gloss: "人工智能", level: 3 },
  { source: "逐渐增加", target: "gradually increase", gloss: "逐渐增加", level: 4 },
  { source: "机器学习", target: "machine learning", gloss: "机器学习", level: 4 },
  { source: "深度学习", target: "deep learning", gloss: "深度学习", level: 5 },
  { source: "用户体验", target: "user experience", gloss: "用户体验", level: 4 },
  { source: "解决方案", target: "solution", gloss: "解决方案", level: 3 },
  { source: "操作系统", target: "operating system", gloss: "操作系统", level: 3 },
  { source: "数据库", target: "database", gloss: "数据库", level: 3 },
  { source: "浏览器", target: "browser", gloss: "浏览器", level: 2 },
  { source: "服务器", target: "server", gloss: "服务器", level: 2 },
  { source: "开发者", target: "developer", gloss: "开发者", level: 3 },
  { source: "应用程序", target: "application", gloss: "应用程序", level: 3 },
  { source: "源代码", target: "source code", gloss: "源代码", level: 3 },
  { source: "开源", target: "open source", gloss: "开源", level: 3 },
  { source: "功能", target: "feature", gloss: "功能", level: 2 },
  { source: "性能", target: "performance", gloss: "性能", level: 4 },
  { source: "安全", target: "security", gloss: "安全", level: 3 },
  { source: "隐私", target: "privacy", gloss: "隐私", level: 3 },
  { source: "数据", target: "data", gloss: "数据", level: 1 },
  { source: "网络", target: "network", gloss: "网络", level: 2 },
  { source: "模型", target: "model", gloss: "模型", level: 2 },
  { source: "算法", target: "algorithm", gloss: "算法", level: 4 },
  { source: "工具", target: "tool", gloss: "工具", level: 1 },
  { source: "项目", target: "project", gloss: "项目", level: 2 },
  { source: "产品", target: "product", gloss: "产品", level: 2 },
  { source: "服务", target: "service", gloss: "服务", level: 2 },
  { source: "设计", target: "design", gloss: "设计", level: 2 },
  { source: "系统", target: "system", gloss: "系统", level: 2 },
  { source: "技术", target: "technology", gloss: "技术", level: 3 },
  { source: "效率", target: "efficiency", gloss: "效率", level: 4 },
  { source: "质量", target: "quality", gloss: "质量", level: 3 },
  { source: "环境", target: "environment", gloss: "环境", level: 3 },
  { source: "内容", target: "content", gloss: "内容", level: 2 },
  { source: "上下文", target: "context", gloss: "上下文", level: 4 },
  { source: "语言", target: "language", gloss: "语言", level: 2 },
  { source: "学习", target: "learning", gloss: "学习", level: 2 },
  { source: "理解", target: "understand", gloss: "理解", level: 2 },
  { source: "阅读", target: "reading", gloss: "阅读", level: 2 },
  { source: "选择", target: "choose", gloss: "选择", level: 2 },
  { source: "支持", target: "support", gloss: "支持", level: 2 },
  { source: "提供", target: "provide", gloss: "提供", level: 2 },
  { source: "创建", target: "create", gloss: "创建", level: 2 },
  { source: "增加", target: "increase", gloss: "增加", level: 3 },
  { source: "减少", target: "reduce", gloss: "减少", level: 3 },
  { source: "改善", target: "improve", gloss: "改善", level: 3 },
  { source: "影响", target: "impact", gloss: "影响", level: 3 },
  { source: "结果", target: "result", gloss: "结果", level: 2 },
  { source: "原因", target: "reason", gloss: "原因", level: 2 },
  { source: "问题", target: "problem", gloss: "问题", level: 2 },
  { source: "方法", target: "approach", gloss: "方法、途径", level: 4 },
  { source: "目标", target: "goal", gloss: "目标", level: 2 },
  { source: "计划", target: "plan", gloss: "计划", level: 1 },
  { source: "需求", target: "requirement", gloss: "需求", level: 4 },
  { source: "风险", target: "risk", gloss: "风险", level: 3 },
  { source: "机会", target: "opportunity", gloss: "机会", level: 4 },
  { source: "变化", target: "change", gloss: "变化", level: 2 },
  { source: "过程", target: "process", gloss: "过程", level: 3 },
  { source: "关键", target: "essential", gloss: "关键的", level: 5 },
  { source: "重要", target: "important", gloss: "重要的", level: 2 },
  { source: "复杂", target: "complex", gloss: "复杂的", level: 3 },
  { source: "简单", target: "simple", gloss: "简单的", level: 1 },
  { source: "稳定", target: "stable", gloss: "稳定的", level: 3 },
  { source: "灵活", target: "flexible", gloss: "灵活的", level: 4 },
  { source: "可靠", target: "reliable", gloss: "可靠的", level: 4 },
  { source: "当前", target: "current", gloss: "当前的", level: 2 },
  { source: "未来", target: "future", gloss: "未来", level: 2 },
  { source: "通常", target: "usually", gloss: "通常", level: 2 },
  { source: "可能", target: "potentially", gloss: "可能地", level: 5 },
  { source: "特别", target: "particularly", gloss: "特别地", level: 5 },
  { source: "逐渐", target: "gradually", gloss: "逐渐地", level: 4 },
  { source: "准确", target: "accurate", gloss: "准确的", level: 4 },
  { source: "自动", target: "automatically", gloss: "自动地", level: 4 },
  { source: "免费", target: "free", gloss: "免费的", level: 1 },
  { source: "用户", target: "user", gloss: "用户", level: 1 },
  { source: "网站", target: "website", gloss: "网站", level: 1 },
  { source: "页面", target: "page", gloss: "页面", level: 1 },
  { source: "文本", target: "text", gloss: "文本", level: 1 },
  { source: "单词", target: "word", gloss: "单词", level: 1 },
  { source: "短语", target: "phrase", gloss: "短语", level: 3 },
  { source: "句子", target: "sentence", gloss: "句子", level: 2 },
];
